greek_alp = {
	"Alpha" : "Alp",
	"Beta" : "Bet",
	"Gamma" : "Gam",
	"Delta" : "Del",
	"Epsilon" : "Eps",
	"Zeta" : "Zet",
	"Eta" : "Eta",
	"Theta" : "The",
	"Iota" : "Iot",
	"Kappa" : "Kap",
	"Lambda" : "Lam",
	"Mu" : "Mu ",
	"Nu" : "Nu ",
	"Xi" : "Xi ",
	"Omicron" : "Omi",
	"Pi" : "Pi ",
	"Rho" : "Rho",
	"Sigma" : "Sig",
	"Tau" : "Tau",
	"Upsilon" : "Ups",
	"Phi" : "Phi",
	"Chi" : "Chi",
	"Psi" : "Psi",
	"Omega" : "Ome",
}

greek_unicode = {
	"Alp" : "\\u03b1",
	"Bet" : "\\u03b2",
	"Gam" : "\\u03b3",
	"Del" : "\\u03b4",
	"Eps" : "\\u03b5",
	"Zet" : "\\u03b6",
	"Eta" : "\\u03b7",
	"The" : "\\u03b8",
	"Iot" : "\\u03b9",
	"Kap" : "\\u03ba",
	"Lam" : "\\u03bb",
	"Mu " : "\\u03bc",
	"Nu " : "\\u03bd",
	"Xi " : "\\u03be",
	"Omi" : "\\u03bf",
	"Pi " : "\\u03c0",
	"Rho" : "\\u03c1",
	"Sig" : "\\u03c3",
	"Tau" : "\\u03c4",
	"Ups" : "\\u03c5",
	"Phi" : "\\u03c6",
	"Chi" : "\\u03c7",
	"Psi" : "\\u03c8",
	"Ome" : "\\u03c9",
}
