pname = {
	"The1Eri" : "Acamar",
	"Alp Eri" : "Achernar",
	"Eta Cas" : "Achird",
	"Bet1Sco" : "Acrab",
	"Alp1Cru" : "Acrux",
	"Alp Cnc" : "Acubens",
	"Eps CMa" : "Adhara",
	"Eps Tau" : "Ain",
	"Eta Lyr" : "Aladfar",
	"Mu  Lyr" : "Alathfar",
	"Pi  Sgr" : "Albaldah",
	"Eps Aqr" : "Albali",
	"Bet1Cyg" : "Albireo",
	"Alp Crv" : "Alchiba",
	" 80    UMa" : "Alcor",
	"Eta Tau" : "Alcyone",
	"Alp Tau" : "Aldebaran",
	"Alp Cep" : "Alderamin",
	"Zet Leo" : "Adhafera", # Aldhafera
	"Gam Gru" : "Aldhanab",
	"Zet Dra" : "Aldhibah",
	"Del Dra" : "Altais", # Aldib
	"Del Cyg" : "Al Fawaris",
	"Alp CrA" : "Alfecca Meridiana",
	"Bet Cep" : "Alfirk",
	"Alp2Cap" : "Algiedi", # Al Giedi, Giedi
	"Gam Peg" : "Algenib",
	"Gam1Leo" : "Algieba",
	"Bet Per" : "Algol",
	"Del Crv" : "Algorab",
	"Gam Gem" : "Alhena",
	"Zet UMi" : "Alifa al Farkadain",
	"Eps UMa" : "Alioth",
	"Eta UMa" : "Alkaid", # Benetnasch
	"The Col" : "Al Kurud",
	"Rho2Cep" : "Al Kalb al Rai",
	"Mu 1Boo" : "Alkalurops",
	"Chi UMa" : "Al Kaphrah",
	"Alp Crt" : "Alkes",
	"Xi  Cep" : "Alkurah",
	"Gam1And" : "Almach", # Alamak
	"Kap Leo" : "Al Minliar al Asad",
	"Alp Gru" : "Al Nair",
	"Gam2Sgr" : "Alnasl", # Nash
	"Eps Ori" : "Alnilam",
	"HR1948" : "Alnitak",
	"Tau Sco" : "Alniyat",
	"Sig Sco" : "Al Niyat",
	"Alp Hya" : "Alphard",
	"Alp CrB" : "Alphecca",
	"Alp And" : "Alpheratz",
	"HR6370" : "Arrakis", # Alrakis
	"HR 596" : "Alrischa",
	"Sig Dra" : "Alsafi",
	" 31    Lyn" : "Alsciaukat",
	"Bet Aql" : "Alshain",
	"Nu  Cap" : "Alshat",
	"Alp Aql" : "Altair",
	"Bet Cnc" : "Altarf",
	"Lam Leo" : "Alterf",
	"Lam Aql" : "Al Thalimain",
	"Eta CMa" : "Aludra",
	"HR4375" : "Alula Australis",
	"Nu  UMa" : "Alula Borealis",
	"The1Ser" : "Alya",
	"Xi  Gem" : "Alzir",
	"The Aqr" : "Ancha",
	"Tau2Eri" : "Angetenar",
	"Alp Phe" : "Ankaa",
	"Alp Sco" : "Antares",
	"Eta UMi" : "Anwar al Farkadain",
	"Alp Boo" : "Arcturus",
	"Bet1Sgr" : "Arkab Prior",
	"Bet2Sgr" : "Arkab Posterior",
	"Eta Cap" : "Arm",
	"Alp Lep" : "Arneb",
	"Zet Sgr" : "Ascella", # Askella
	"Del Cnc" : "Asellus Australis",
	"Gam Cnc" : "Asellus Borealis",
	"The Boo" : "Asellus Primus",
	"Iot Boo" : "Asellus Secundus",
	"Kap2Boo" : "Asellus Tertius",
	"Eps Hya" : "Ashlesha",
	"Iot Car" : "Aspidiske",
	" 21    Tau" : "Asterope",
	"Omi Per" : "Atik",
	" 27    Tau" : "Atlas",
	"Alp TrA" : "Atria",
	"Del Vir" : "Auva", # Minelava
	"Eps Car" : "Avior",
	"Pi 1Cyg" : "Azelfafage",
	"Eta Eri" : "Azha",
	"Xi  Pup" : "Azmidiske",
	"The Peg" : "Baham", # Biham
	"Zet Cet" : "Baten Kaitos",
	"Omi1Eri" : "Beid",
	"Gam Ori" : "Bellatrix",
	"Alp Ori" : "Betelgeuse",
	"Bet TrA" : "Betria",
	" 41    Ari" : "Bharani",
	"  5    Tau" : "Birhan Isat",
	"Del Ari" : "Botein",
	"Sig Lib" : "Brachium",
	"Xi  Aqr" : "Bunda",
	"Alp Car" : "Canopus",
	"Alp Aur" : "Capella", # Alhajoth
	"Bet Cas" : "Caph",
	"HR2891" : "Castor", # Ras Thaoum
	"Bet Oph" : "Cebalrai", # Cheleb
	" 16    Tau" : "Celaeno",
	"Bet CVn" : "Chara", # Asterion
	"The Leo" : "Chertan", # Chort
	"Bet Ser" : "Chow",
	"Alp2CVn" : "Cor Caroli",
	"Bet Eri" : "Cursa",
	"Bet Cap" : "Dabih",
	"Del Cru" : "Decrux",
	"Alp Cyg" : "Deneb", # Arided
	"Del Cap" : "Deneb Algedi", # Scheddi
	"Eps Del" : "Deneb Dulfim",
	"Zet Aql" : "Deneb el Okab",
	"Bet Cet" : "Deneb Kaitos", # Diphda
	"Iot Cet" : "Deneb Kaitos Schemali",
	"Bet Leo" : "Denebola",
	"Eta Cet" : "Dheneb",
	"HR4968" : "Diadem",
	"Del Sco" : "Dschubba",
	"Alp UMa" : "Dubhe",
	"Iot Dra" : "Edasich",
	" 17    Tau" : "Electra",
	"Bet Tau" : "Elnath",
	"Gam Dra" : "Eltanin", # Etamin
	"Eps Peg" : "Enif",
	"Gam Cep" : "Errai", # Alrai
	"Alp PsA" : "Fomalhaut",
	"Bet Psc" : "Fum al Samakah",
	"Zet CMa" : "Furud",
	"HR4763" : "Gacrux",
	"Mu  Cep" : "Garnet Star",
	"Gam TrA" : "Gatria",
	"Lam Dra" : "Gianfar",
	"Gam Crv" : "Gienah Gurab",
	"Eps Cyg" : "Giennah",
	"Kap Sco" : "Girtab",
	"Bet CMi" : "Gomeisa",
	"Rho Per" : "Gorgonea Tertia",
	"HR5978" : "Graffias",
	"Xi  Dra" : "Grumium",
	"Bet Cen" : "Hadar",
	"Sig Pup" : "Hadir",
	"Zet Aur" : "Sadatoni", # Hoedus, Haedus, Azaleh
	"Eps Aur" : "Haldus",
	"Alp Ari" : "Hamal",
	"Iot Aur" : "Hassaleh", # Kabdhilinan
	"Alp Hyi" : "Head of Hydrus",
	"Zet Vir" : "Heze",
	"Eta Aur" : "Hoedus II",
	"Zet Peg" : "Homam",
	"Gam Tau" : "Hyadum I",
	"Del1Tau" : "Hyadum II",
	"Zet Hya" : "Hydrobius",
	"HR5055" : "Izar", # Pulcherrima
	"HR6027" : "Jabbah",
	"Kap Peg" : "Jih",
	"Gam Cet" : "Kaffaljidhma",
	"Ome Her" : "Kajam",
	"Eps Cap" : "Kastra",
	"Eps Sgr" : "Kaus Australis",
	"Lam Sgr" : "Kaus Borealis",
	"Del Sgr" : "Kaus Media", # Media
	"Omi2Eri" : "Keid",
	"Alp Equ" : "Kitalpha",
	"Del3Tau" : "Kleeia",
	"Bet UMi" : "Kochab",
	"Bet Her" : "Kornephoros",
	"Bet Crv" : "Kraz",
	"Eta Psc" : "Kullat Nunu",
	"Nu 2Dra" : "Kuma",
	"HR4846" : "La Superba",
	"Ups Sco" : "Lesath",
	"Alp Vul" : "Lucida Anseris",
	"Lam Her" : "Maasym",
	"The Aur" : "Mahasim",
	" 20    Tau" : "Maia",
	"The Cas" : "Marfark",
	"Lam Oph" : "Marfik",
	"Alp Peg" : "Markab",
	"Eta Peg" : "Matar",
	"Eps Gem" : "Mebsuta",
	"Del UMa" : "Megrez",
	"HR1879" : "Meissa", # Heka
	"Zet Gem" : "Mekbuda",
	"Xi  Per" : "Menchib",
	"Bet Aur" : "Menkalinan",
	"Alp Cet" : "Menkar", # Menkab
	"The Cen" : "Menkent",
	"Zet Per" : "Menkib",
	"Bet UMa" : "Merak",
	" 38    Boo" : "Merga",
	" 23    Tau" : "Merope",
	"Gam2Ari" : "Mesarthim",
	"Bet Car" : "Miaplacidus",
	"Bet Cru" : "Mimosa", # Becrux
	"Sig Hya" : "Minchir",
	"Eps Crv" : "Minkar",
	"HR1852" : "Mintaka",
	"Omi Cet" : "Mira",
	"Bet And" : "Mirach",
	"Eta Per" : "Miram",
	"Alp Per" : "Mirfak",
	"Bet CMa" : "Mirzam", # Murzim
	"Kap Per" : "Misam",
	"HR5054" : "Mizar",
	"Alp Tri" : "Mothallah", # Elmuthalleth
	"Gam CMa" : "Muliphein",
	"Gam Cen" : "Muhlifain",
	"Eta Boo" : "Muphrid",
	"Omi UMa" : "Muscida",
	"Iot Ori" : "Nair Al Saif",
	"Zet Pup" : "Naos",
	"Gam Cap" : "Nashira",
	"Gam Cas" : "Navi",
	"Bet Boo" : "Nekkar",
	" 51    And" : "Nembus",
	"Mu  Lep" : "Neshmet",
	"Bet Lep" : "Nihal",
	"Sig Sgr" : "Nunki",
	"Bet CrB" : "Nusakan",
	"Pi  Cap" : "Okul",
	"Alp Pav" : "Peacock",
	"Alp Col" : "Phact",
	"Gam UMa" : "Phad",
	"Gam UMi" : "Pherkad",
	" 28    Tau" : "Pleione",
	"Alp UMi" : "Polaris", # Alruccabah
	"Sig Oct" : "Polaris Australis",
	"Bet Gem" : "Pollux",
	"HR4825" : "Porrima", # Arich
	" 46    LMi" : "Praecipua",
	"Alp CMi" : "Procyon",
	"Del Eri" : "Rana",
	"Alp1Her" : "Ras Algethi",
	"Alp Oph" : "Ras Alhague",
	"Eps Leo" : "Ras Elased Australis",
	"Mu  Leo" : "Rasalas",
	"Bet Dra" : "Rastaban", # Alwaid
	"Gam2Vel" : "Regor",
	"Alp Leo" : "Regulus",
	"Bet Ori" : "Rigel",
	"Alp1Cen" : "Rigil Kentaurus", # Toliman
	"Mu  Vir" : "Rijl al Awwa",
	"Bet Del" : "Rotanev",
	"Ome2Cyg" : "Ruchba",
	"Del Cas" : "Ruchbah", # Ksora
	"Alp Sgr" : "Rukbat", # Alrami
	"Eta Oph" : "Sabik",
	"Gam Aqr" : "Sadachbia",
	"Mu  Peg" : "Sadalbari",
	"Alp Aqr" : "Sadalmelik",
	"Bet Aqr" : "Sadalsuud",
	"Eps Eri" : "Sadira",
	"Gam Cyg" : "Sadr",
	"Kap Ori" : "Saiph",
	"Tau Peg" : "Salm",
	"The Sco" : "Sargas",
	"Del Her" : "Sarin",
	"The UMa" : "Sarir",
	"Eps Lep" : "Sasin",
	" 53    Eri" : "Sceptrum",
	"Bet Peg" : "Scheat",
	"Alp Cas" : "Schedir",
	"Eps Cas" : "Segin",
	"Gam Boo" : "Seginus",
	"Alp Sge" : "Sham",
	"Lam Sco" : "Shaula",
	"Bet Lyr" : "Sheliak",
	"Bet Ari" : "Sheratan",
	"Nu  Oph" : "Sinistra",
	"Alp CMa" : "Sirius",
	"Kap Aqr" : "Situla",
	"Del Aqr" : "Skat",
	"Alp Vir" : "Spica", # Azimech
	" 22    Tau" : "Sterope II",
	"Alp Del" : "Sualocin",
	"Omi Leo" : "Subra",
	"Lam Vel" : "Suhail",
	"Gam Lyr" : "Sulafat",
	"Iot Vir" : "Syrma",
	"Pi 3Ori" : "Tabit",
	"Kap UMa" : "Talitha Australis",
	"Iot UMa" : "Talitha Borealis", # Dnoces
	"Mu  UMa" : "Tania Australis",
	"Lam UMa" : "Tania Borealis",
	"Gam Aql" : "Tarazet",
	" 19    Tau" : "Taygeta",
	"HR3208" : "Tegmine", 
	"Ome Sgr" : "Terebellum",
	"Mu  Gem" : "Tejat Posterior",
	"Eta Gem" : "Tejat Prior", # Propus
	"Ups Ori" : "Thabit",
	"Ups2Eri" : "Theemin",
	"Alp Dra" : "Thuban",
	"Zet Tau" : "Tien Kwan", # Shurnarkabtishashutu
	"Omi Psc" : "Torcularis Septentrionalis",
	"Phi Vel" : "Tseen Kee",
	"Pi  Pup" : "Tureis",
	"Eps Dra" : "Tyl",
	"Alp Ser" : "Unukalhai",
	"Xi  Tau" : "Ushakaron",
	"Alp Lyr" : "Vega",
	"Eps Vir" : "Vindemiatrix",
	"Del Gem" : "Wasat",
	"Bet Col" : "Wazn",
	"Eps Sco" : "Wei",
	"Del CMa" : "Wezen",
	"Del Oph" : "Yed Prior",
	"Eps Oph" : "Yed Posterior",
	"Del UMi" : "Yildun",
	"Eta Vir" : "Zaniah",
	"Gam Eri" : "Zaurak",
	"Bet Vir" : "Zavijava", # Alaraph
	"Del Leo" : "Zosma", # Duhr
	"Gam Lib" : "Zuben-el-Akrab",
	"Del Lib" : "Zuben-el-Akribi",
	"Alp2Lib" : "Zubenelgenubi",
	"Bet Lib" : "Zubeneschamali" # Lanx Australis
}
